#!/bin/sh
# Installs Watchtower with Docker Compose:
#
#   curl -fsSL https://raw.githubusercontent.com/olucurious/watchtower/main/install.sh | sh
#
# It creates ./watchtower with compose.yaml and an .env of generated secrets,
# starts Watchtower and Postgres, and prints the address and the one-time
# setup code for creating the administrator. Running it again upgrades to
# the latest image; an existing .env is never overwritten.
#
# Settings (environment variables):
#   WATCHTOWER_DIR      where to install (default: ./watchtower)
#   WATCHTOWER_PORT     host port for a new install (default: 8080)
#   WATCHTOWER_VERSION  image tag to run (default: latest)
set -eu

REPO_RAW=${WATCHTOWER_REPO_RAW:-https://raw.githubusercontent.com/olucurious/watchtower/main}
DIR=${WATCHTOWER_DIR:-watchtower}

say() { printf '%s\n' "$*"; }
fail() {
	printf 'watchtower install: %s\n' "$*" >&2
	exit 1
}

command -v docker >/dev/null 2>&1 || fail "Docker is required: https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required (the 'docker compose' command)"
docker info >/dev/null 2>&1 || fail "cannot reach Docker; is it running, and is this user allowed to use it?"

fetch() {
	if command -v curl >/dev/null 2>&1; then
		curl -fsSL "$1"
	elif command -v wget >/dev/null 2>&1; then
		wget -qO- "$1"
	else
		fail "curl or wget is required"
	fi
}

# secret prints n random bytes as hex.
secret() { od -An -N"$1" -tx1 /dev/urandom | tr -d ' \n'; }

# setting prints a value from .env.
setting() { sed -n "s/^$1=//p" .env | tail -n 1; }

mkdir -p "$DIR"
cd "$DIR"

# Never take over another project's folder: self-hosters often keep other
# tools (including containrrr's Watchtower) in a folder called watchtower.
ours() { grep -q 'ghcr.io/olucurious/watchtower' "$1" 2>/dev/null; }
for f in compose.yaml compose.yml docker-compose.yaml docker-compose.yml; do
	if [ -f "$f" ] && ! ours "$f"; then
		fail "$(pwd)/$f belongs to another project, so Watchtower will not install here. Choose another folder, for example:
  curl -fsSL $REPO_RAW/install.sh | WATCHTOWER_DIR=watchtower-errors sh"
	fi
done
if [ -f .env ] && ! grep -q '^WATCHTOWER_SECRET_KEY=' .env; then
	fail "$(pwd)/.env belongs to another project, so Watchtower will not install here. Choose another folder, for example:
  curl -fsSL $REPO_RAW/install.sh | WATCHTOWER_DIR=watchtower-errors sh"
fi

fetch "$REPO_RAW/compose.yaml" >compose.yaml.tmp || fail "could not download compose.yaml from $REPO_RAW"
mv compose.yaml.tmp compose.yaml

if [ -f .env ]; then
	say "Keeping the existing $DIR/.env."
else
	port=${WATCHTOWER_PORT:-8080}
	project=$(basename "$(pwd)" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9_\n-' '-')
	case $project in
	*-errors) ;;
	*) project=$project-errors ;;
	esac
	(
		umask 077
		cat >.env <<EOF
# Generated by the Watchtower installer. Back this file up with the
# database: WATCHTOWER_SECRET_KEY encrypts stored Slack and Linear
# credentials, and they cannot be read without it.

# A project name of its own, so these containers never collide with another
# project's, whatever this folder is called.
COMPOSE_PROJECT_NAME=$project
WATCHTOWER_DB_PASSWORD=$(secret 16)
WATCHTOWER_SECRET_KEY=$(secret 32)
WATCHTOWER_PORT=$port
# The address people and SDKs use to reach Watchtower. Change it when you
# put Watchtower behind a domain, then run: docker compose up -d
WATCHTOWER_PUBLIC_URL=http://localhost:$port
EOF
	)
	if [ -n "${WATCHTOWER_VERSION:-}" ]; then
		say "WATCHTOWER_VERSION=$WATCHTOWER_VERSION" >>.env
	fi
	say "Created $DIR/.env with generated secrets."
fi

say "Starting Watchtower..."
docker compose pull --quiet --ignore-pull-failures
docker compose up -d

tries=0
until docker compose exec -T watchtower watchtower healthcheck >/dev/null 2>&1; do
	tries=$((tries + 1))
	[ "$tries" -lt 60 ] || fail "Watchtower did not become healthy; see: cd $DIR && docker compose logs watchtower"
	sleep 2
done

url=$(setting WATCHTOWER_PUBLIC_URL)
# A fresh code, issued only while no account exists.
code=$(docker compose exec -T watchtower watchtower setup-code 2>/dev/null | sed -n 's/^Setup code: //p') || true

say ""
say "Watchtower is running at $url"
if [ -n "$code" ]; then
	say ""
	say "Open it and create your administrator with this setup code:"
	say ""
	say "    $code"
else
	say "Sign in with your existing account."
fi
say ""
say "Files are in $(pwd). To upgrade later, run this installer again."
